//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17351
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData
{


	public partial class ForeignKey_EditField
	{

		protected global::System.Web.UI.WebControls.DropDownList DropDownList1;

		protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

		protected global::System.Web.DynamicData.DynamicValidator DynamicValidator1;
	}
}
